# Generated by Django 3.2 on 2021-05-20 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=100)),
                ('on_discount', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinValueValidator(5)])),
            ],
        ),
    ]
