# Generated by Django 3.2 on 2021-05-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
