# Generated by Django 3.2 on 2021-05-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapi', '0002_alter_courses_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
