# Generated by Django 3.2 on 2021-05-22 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapi', '0006_auto_20210522_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
